Repository YAPP-19th/Web-Team-1-Frontend, pull requests merged in 2021-11, with the labels that each got.

#4 [GILJOB-1] 프로젝트 storybook 개발 환경 구성 및 storybook CI 구성
  .github/workflows/Storybook-CI.yml
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/StorybookTutorial/button.scss
  src/components/StorybookTutorial/button.stories.tsx
  src/components/StorybookTutorial/index.tsx
Labels: environment

#3 [GILJOB-1] 프론트엔드 개발 환경 수정
  .babelrc
  .github/workflows/Storybook-CI.yml
  .storybook/main.js
  .storybook/preview.js
  jest.config.js
  package-lock.json
  package.json
  src/components/StorybookTutorial/button.scss
  src/components/StorybookTutorial/button.stories.tsx
  src/components/StorybookTutorial/index.tsx
Labels: environment, hotfix

#6 [GILJOB-44] Card 컴포넌트 제작 외 다수
  .eslintrc
  config/webpack/webpack.dev.js
  config/webpack/webpack.prod.js
  src/atoms/Badge/Badge.tsx
  src/atoms/Badge/badge.stories.tsx
  src/atoms/Badge/index.ts
  src/atoms/Badge/style.scss
  src/atoms/Text/Text.tsx
  src/atoms/Text/index.ts
  src/atoms/Text/style.scss
  src/atoms/Text/text.stories.tsx
  src/components/Card/Card.tsx
  src/components/Card/card.stories.tsx
  src/components/Card/index.ts
  src/components/Card/style.scss
  src/index.tsx
  src/styles/_color.scss
  src/styles/_font.scss
  src/styles/_variable.scss
  src/styles/index.scss
  src/utils/colorEnum.ts
  src/utils/colorMap.ts
  src/utils/fontSize.ts
  src/utils/index.ts
Labels: environment, feature

#7 [GILJOB-38] 라우터 기초 설정
  config/webpack/webpack.dev.js
  src/App.test.tsx
  src/App.tsx
  src/index.tsx
  src/pages/Landing/index.tsx
  src/pages/Login/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/Profile/index.tsx
  src/pages/Quest/index.tsx
Labels: feature

#8 [GILJOB-38] footer 컴포넌트 제작
  src/App.tsx
  src/components/Footer/footer.stories.tsx
  src/components/Footer/index.tsx
  src/components/Footer/style.scss
  src/components/Header/header.stories.tsx
  src/components/Header/headerItems.ts
  src/components/Header/index.scss
  src/components/Header/index.tsx
  src/components/Header/style.scss
  src/components/SearchBar/index.scss
  src/components/SearchBar/index.tsx
  src/components/SearchBar/searchBar.stories.tsx
  src/components/SearchBar/style.scss
  src/components/StorybookTutorial/button.scss
  src/components/StorybookTutorial/button.stories.tsx
  src/components/StorybookTutorial/index.tsx
  src/components/index.ts
  src/styles/_color.scss
Labels: feature

#9 [GILJOB-50] fix: 글꼴 장평 추가
  src/styles/index.scss
Labels: hotfix

#10 [GILJOB-50] 랜딩페이지 완성
  src/assets/images/character.svg
  src/assets/images/icon.svg
  src/assets/images/lighthouse.svg
  src/assets/images/map.svg
  src/assets/images/profile.svg
  src/assets/images/ships.svg
  src/assets/images/wave_blue.svg
  src/assets/images/wave_gray.svg
  src/assets/images/wave_navy.svg
  src/atoms/Text/Text.tsx
  src/components/Footer/index.tsx
  src/components/Footer/style.scss
  src/components/Header/index.tsx
  src/components/Header/list.ts
  src/components/Header/style.scss
  src/hooks/useScrollCount.ts
  src/pages/Landing/Landing.stories.tsx
  src/pages/Landing/index.tsx
  src/pages/Landing/templates/Content/index.tsx
  src/pages/Landing/templates/Content/style.scss
  src/pages/Landing/templates/Contents/index.tsx
  src/pages/Landing/templates/Contents/list.ts
  src/pages/Landing/templates/Contents/style.scss
  src/pages/Landing/templates/Count/index.tsx
  src/pages/Landing/templates/Count/list.ts
  src/pages/Landing/templates/Count/style.scss
  src/pages/Landing/templates/Main/index.tsx
  src/pages/Landing/templates/Main/style.scss
  src/pages/Landing/templates/Sub/index.tsx
  src/pages/Landing/templates/Sub/style.scss
  src/pages/Landing/templates/Wave/index.tsx
  src/pages/Landing/templates/Wave/style.scss
  src/pages/Landing/templates/index.ts
Labels: feature

#13 [GILJOB-80] normalize.scss 추가 및 index.tsx 스타일 지정 이슈 해결
  src/index.scss
  src/index.tsx
  src/normalize.scss
  src/styles/index.scss
Labels: hotfix

#16 [GILJOB-81] Storybook CSS 관련 이슈 해결
  .storybook/preview.js
  config/webpack/webpack.base.js
  package.json
  src/components/atoms/Badge/badge.stories.tsx
  src/components/atoms/SearchBar/searchBar.stories.tsx
  src/components/atoms/SearchBar/style.scss
  src/components/atoms/Text/text.stories.tsx
  src/components/molecules/Card/card.stories.tsx
  src/components/molecules/Footer/footer.stories.tsx
  src/components/molecules/Header/header.stories.tsx
  src/index.scss
  src/styles/_font.scss
  src/styles/_variable.scss
  src/styles/index.scss
Labels: urgent, hotfix

#17 [GILJOB-68] 로그인 페이지 구현 완료
  @types/custom-types/index.d.ts
  src/App.test.tsx
  src/App.tsx
  src/assets/images/login.png
  src/assets/images/map.png
  src/assets/images/map.svg
  src/assets/images/ships.png
  src/assets/images/ships.svg
  src/components/atoms/Badge/badge.stories.tsx
  src/components/atoms/Badge/index.ts
  src/components/atoms/Badge/index.tsx
  src/components/atoms/Text/index.ts
  src/components/atoms/Text/index.tsx
  src/components/atoms/Text/text.stories.tsx
  src/components/atoms/index.ts
  src/components/molecules/Card/card.stories.tsx
  src/components/molecules/Card/index.ts
  src/components/molecules/Card/index.tsx
  src/components/molecules/Content/index.tsx
  src/components/molecules/Footer/index.tsx
  src/components/molecules/Footer/style.scss
  src/components/molecules/Header/index.tsx
  src/components/molecules/index.ts
  src/pages/Landing/Contents/index.tsx
  src/pages/Landing/Contents/list.ts
  src/pages/Landing/Count/index.tsx
  src/pages/Landing/Landing.stories.tsx
  src/pages/Landing/Main/index.tsx
  src/pages/Landing/Main/style.scss
  src/pages/Landing/Sub/index.tsx
  src/pages/Landing/Sub/style.scss
  src/pages/Login/Login.stories.tsx
  src/pages/Login/index.tsx
  src/pages/Login/style.scss
  src/styles/_color.scss
Labels: feature

#18 [GILJOB-84] 기존 컴포넌트 수정 및 새로운 컴포넌트 개발 완료
  @types/custom-types/index.d.ts
  src/assets/images/Lv1.svg
  src/assets/images/Lv2.svg
  src/assets/images/Lv3.svg
  src/assets/images/Lv4.svg
  src/assets/images/Lv5.svg
  src/assets/images/bg_quest.png
  src/assets/images/logo.svg
  src/assets/images/paper.png
  src/components/atoms/Badge/badge.stories.tsx
  src/components/atoms/Badge/index.tsx
  src/components/atoms/Badge/style.scss
  src/components/atoms/Button/button.stories.tsx
  src/components/atoms/Button/index.tsx
  src/components/atoms/Button/style.scss
  src/components/atoms/Icon/icon.stories.tsx
  src/components/atoms/Icon/index.tsx
  src/components/atoms/Icon/style.scss
  src/components/atoms/Text/index.tsx
  src/components/atoms/Text/style.scss
  src/components/atoms/Text/text.stories.tsx
  src/components/atoms/index.ts
  src/components/molecules/Author/author.stories.tsx
  src/components/molecules/Author/index.tsx
  src/components/molecules/Author/style.scss
  src/components/molecules/Card/card.stories.tsx
  src/components/molecules/Card/index.tsx
  src/components/molecules/Card/style.scss
  src/components/molecules/Content/index.tsx
  src/components/molecules/Header/index.tsx
  src/components/molecules/Paper/index.tsx
  src/components/molecules/Paper/paper.stories.tsx
  src/components/molecules/Paper/style.scss
  src/components/molecules/index.ts
  src/pages/Landing/Main/index.tsx
  src/pages/Landing/Sub/index.tsx
  src/pages/Login/index.tsx
  src/pages/Login/style.scss
Labels: feature, refactor

#21 [GILJOB-73] 퀘스트 목록(로드맵•퀘스트) 페이지 구성
  package-lock.json
  package.json
  src/components/atoms/MenuBar/index.tsx
  src/components/atoms/MenuBar/menubar.stories.tsx
  src/components/atoms/MenuBar/style.scss
  src/components/atoms/Pagination/index.tsx
  src/components/atoms/Pagination/pagination.stories.tsx
  src/components/atoms/Pagination/style.scss
  src/components/atoms/SearchBar/style.scss
  src/components/atoms/index.ts
  src/components/molecules/Card/style.scss
  src/components/molecules/Header/index.tsx
  src/components/organisms/Carousel/carousel.stories.tsx
  src/components/organisms/Carousel/index.tsx
  src/components/organisms/Carousel/style.scss
  src/components/organisms/index.ts
  src/pages/Landing/Sub/index.tsx
  src/pages/Landing/Sub/style.scss
  src/pages/Quest/Quest.stories.tsx
  src/pages/Quest/QuestList/index.tsx
  src/pages/Quest/QuestList/style.scss
  src/pages/Quest/RoadmapList/index.tsx
  src/pages/Quest/RoadmapList/style.scss
  src/pages/Quest/index.tsx
Labels: feature, refactor

#23 [GILJOB-84] 기존 컴포넌트 수정 및 새로운 컴포넌트 개발 완료
  src/components/atoms/Button/button.stories.tsx
  src/components/atoms/Button/style.scss
  src/components/molecules/Author/style.scss
  src/components/molecules/Paper/index.tsx
  src/components/molecules/Paper/style.scss
  src/pages/Login/Login.stories.tsx
  src/pages/Login/index.tsx
  src/pages/Login/style.scss
Labels: feature, error
