Repository YAPP-19th/Web-Team-1-Frontend, pull requests merged in 2021-12, with the labels that each got.

#24 [GILJOB-54] Profile 컴포넌트 제작
  src/assets/images/achievement_1.svg
  src/assets/images/achievement_2.svg
  src/components/atoms/AchievementBadge/achievementBadge.stories.tsx
  src/components/atoms/AchievementBadge/index.tsx
  src/components/atoms/AchievementBadge/style.scss
  src/components/atoms/AchievementIcon/achievementIcon.stories.tsx
  src/components/atoms/AchievementIcon/index.tsx
  src/components/atoms/AchievementIcon/style.scss
  src/components/atoms/Box/box.stories.tsx
  src/components/atoms/Box/index.tsx
  src/components/atoms/Box/style.scss
  src/components/atoms/Form/form.stories.tsx
  src/components/atoms/Form/index.tsx
  src/components/atoms/Form/style.scss
  src/components/atoms/ProgressBar/index.tsx
  src/components/atoms/ProgressBar/style.scss
  src/components/atoms/index.ts
  src/components/molecules/Mypage/index.tsx
  src/components/molecules/Mypage/mypage.stories.tsx
  src/components/molecules/Mypage/style.scss
  src/components/molecules/index.ts
  src/pages/Profile/index.tsx
  src/pages/Profile/style.scss
Labels: feature

#30 [GILJOB-84] Header 컴포넌트, Quest 페이지 관련 이슈 해결
  package-lock.json
  src/components/atoms/MenuBar/style.scss
  src/components/molecules/Header/index.tsx
  src/components/molecules/Header/style.scss
  src/components/molecules/Paper/index.tsx
  src/pages/Quest/QuestList/style.scss
  src/pages/Quest/RoadmapList/style.scss
Labels: hotfix

#29 [GILJOB-68] 랜딩페이지 이슈 해결
  src/pages/Landing/Count/index.tsx
  src/pages/Landing/Count/style.scss
Labels: hotfix

#28 [GILJOB-68] 컴포넌트 추가 및 퀘스트 생성 페이지 제작 완료
  @types/custom-types/index.d.ts
  README.md
  config/webpack/webpack.base.js
  package-lock.json
  package.json
  src/App.tsx
  src/components/atoms/Board/board.stories.tsx
  src/components/atoms/Board/index.tsx
  src/components/atoms/Board/style.ts
  src/components/atoms/Button/button.stories.tsx
  src/components/atoms/Button/index.tsx
  src/components/atoms/Button/style.scss
  src/components/atoms/Dropdown/dropdown.stories.tsx
  src/components/atoms/Dropdown/index.tsx
  src/components/atoms/Dropdown/list.ts
  src/components/atoms/Dropdown/style.scss
  src/components/atoms/Editor/editor.stories.tsx
  src/components/atoms/Editor/index.tsx
  src/components/atoms/Input/index.tsx
  src/components/atoms/Input/input.stories.tsx
  src/components/atoms/Input/style.scss
  src/components/atoms/List/index.tsx
  src/components/atoms/List/list.stories.tsx
  src/components/atoms/List/style.scss
  src/components/atoms/MenuBar/style.scss
  src/components/atoms/Uploader/index.tsx
  src/components/atoms/Uploader/style.scss
  src/components/atoms/Uploader/uploader.stories.tsx
  src/components/atoms/index.ts
  src/components/molecules/DragDrop/dragdrop.stories.tsx
  src/components/molecules/DragDrop/index.tsx
  src/components/molecules/DragDrop/style.scss
  src/components/molecules/Hashtag/hashtag.stories.tsx
  src/components/molecules/Hashtag/index.tsx
  src/components/molecules/Hashtag/style.scss
  src/components/molecules/Header/index.tsx
  src/components/molecules/Header/style.scss
  src/components/molecules/Paper/index.tsx
  src/components/molecules/index.ts
  src/pages/Landing/Count/index.tsx
  src/pages/Landing/Count/style.scss
  src/pages/Quest/QuestList/style.scss
  src/pages/Quest/RoadmapList/style.scss
  src/pages/QuestCreate/QuestDetail/index.tsx
  src/pages/QuestCreate/QuestDetail/style.scss
  src/pages/QuestCreate/QuestMain/index.tsx
  src/pages/QuestCreate/QuestMain/style.scss
  src/pages/QuestCreate/QuestSub/index.tsx
  src/pages/QuestCreate/QuestSub/style.scss
  src/pages/QuestCreate/index.tsx
  src/pages/QuestCreate/questCreate.stories.tsx
  src/pages/QuestCreate/quest_data.json
  src/pages/QuestCreate/style.scss
  tsconfig.json
Labels: environment, feature

#31 [GILJOB-91] feat: 랜딩페이지 Lottie 적용
  package-lock.json
  package.json
  src/pages/Landing/Main/character.json
  src/pages/Landing/Main/index.tsx
  src/pages/Landing/Main/style.scss
Labels: feature

#33 [GILJOB-68] 로그인 계정 생성 페이지 추가
  src/components/atoms/Dropdown/dropdown.stories.tsx
  src/components/atoms/Dropdown/index.tsx
  src/components/atoms/Textarea/index.tsx
  src/components/atoms/Textarea/style.scss
  src/components/atoms/Textarea/textarea.stories.tsx
  src/components/atoms/index.ts
  src/constants/dropdown/index.ts
  src/pages/Login/Login.stories.tsx
  src/pages/Login/LoginBox/index.tsx
  src/pages/Login/LoginBox/style.scss
  src/pages/Login/SettingBox/index.tsx
  src/pages/Login/SettingBox/style.scss
  src/pages/Login/index.tsx
  src/pages/Login/style.scss
  src/pages/QuestCreate/QuestMain/index.tsx
  src/pages/RoadmapCreate/RoadmapMain/index.tsx
Labels: feature

#36 [GILJOB-94] Roadmap 컴포넌트를 만들었습니다.
  package-lock.json
  src/assets/images/destination.svg
  src/assets/images/paper_big.png
  src/assets/images/ship.svg
  src/assets/images/star.svg
  src/components/organisms/Roadmap/index.tsx
  src/components/organisms/Roadmap/roadmap.stories.tsx
  src/components/organisms/Roadmap/style.scss
  src/components/organisms/index.ts
Labels: feature

#37 [GILJOB-68] Redux Toolkit 임시 연결
  .storybook/preview.js
  src/App.tsx
  src/assets/lottie/map.json
  src/components/atoms/Dropdown/dropdown.stories.tsx
  src/components/atoms/Dropdown/index.tsx
  src/components/atoms/Editor/index.tsx
  src/components/atoms/Input/index.tsx
  src/components/atoms/List/list.stories.tsx
  src/components/atoms/Toast/index.tsx
  src/components/atoms/Uploader/index.tsx
  src/components/atoms/Uploader/uploader.stories.tsx
  src/components/molecules/DragDrop/dragdrop.stories.tsx
  src/components/molecules/DragDrop/index.tsx
  src/components/molecules/DragDrop/style.scss
  src/components/molecules/Hashtag/hashtag.stories.tsx
  src/components/molecules/Hashtag/index.tsx
  src/components/molecules/Header/header.stories.tsx
  src/constants/dropdown/index.ts
  src/pages/CreateQuest/Detail/index.tsx
  src/pages/CreateQuest/Main/index.tsx
  src/pages/CreateQuest/Main/style.scss
  src/pages/CreateQuest/Sub/index.tsx
  src/pages/CreateQuest/index.tsx
  src/pages/CreateQuest/questCreate.stories.tsx
  src/pages/CreateQuest/quest_data.json
  src/pages/CreateQuest/style.scss
  src/pages/CreateRoadmap/Detail/index.tsx
  src/pages/CreateRoadmap/Detail/style.scss
  src/pages/CreateRoadmap/Main/index.tsx
  src/pages/CreateRoadmap/Main/style.scss
  src/pages/CreateRoadmap/index.tsx
  src/pages/CreateRoadmap/roadmapMain.stories.tsx
  src/pages/CreateRoadmap/roadmap_data.json
  src/pages/CreateRoadmap/style.scss
  src/pages/Landing/Contents/list.ts
  src/pages/Landing/Landing.stories.tsx
  src/pages/Login/SettingBox/index.tsx
  src/pages/Quest/Quest.stories.tsx
  src/pages/QuestCreate/QuestMain/index.tsx
  src/pages/QuestCreate/QuestSub/index.tsx
  src/pages/QuestCreate/questCreate.stories.tsx
  src/pages/RoadmapCreate/RoadmapMain/index.tsx
  src/pages/RoadmapCreate/roadmapMain.stories.tsx
  src/slices/createQuestSlice.ts
  src/slices/createRoadmapSlice.ts
  src/store/index.ts
Labels: feature, question

#35 [GILJOB-110] 프로필 페이지 개발 완료
  src/assets/images/achievement_1.svg
  src/assets/images/achievement_10.svg
  src/assets/images/achievement_2.svg
  src/assets/images/achievement_3.svg
  src/assets/images/achievement_4.svg
  src/assets/images/achievement_5.svg
  src/assets/images/achievement_6.svg
  src/assets/images/achievement_7.svg
  src/assets/images/achievement_8.svg
  src/assets/images/achievement_9.svg
  src/assets/images/edit_icon.svg
  src/assets/images/empty_quest_list.svg
  src/assets/images/profile_box.svg
  src/components/atoms/AchievementBadge/index.tsx
  src/components/atoms/AchievementIcon/style.scss
  src/components/atoms/Box/index.tsx
  src/components/atoms/Box/style.scss
  src/components/atoms/Button/index.tsx
  src/components/atoms/Button/style.scss
  src/components/atoms/Dropdown/index.tsx
  src/components/atoms/Dropdown/style.scss
  src/components/atoms/Form/form.stories.tsx
  src/components/atoms/Form/index.tsx
  src/components/atoms/Form/style.scss
  src/components/atoms/TabBar/index.tsx
  src/components/atoms/TabBar/style.scss
  src/components/atoms/TabBar/tabBar.stories.tsx
  src/components/atoms/Textarea/index.tsx
  src/components/atoms/Textarea/style.scss
  src/components/atoms/index.ts
  src/components/molecules/Mypage/index.tsx
  src/components/molecules/Mypage/mypage.stories.tsx
  src/components/molecules/Mypage/style.scss
  src/components/molecules/ProfileQuestCard/index.tsx
  src/components/molecules/ProfileQuestCard/profileQuestCard.stories.tsx
  src/components/molecules/ProfileQuestCard/style.scss
  src/components/molecules/index.ts
  src/pages/CreateRoadmap/Detail/index.tsx
  src/pages/CreateRoadmap/Detail/style.scss
  src/pages/Profile/Achievement/index.tsx
  src/pages/Profile/Achievement/style.scss
  src/pages/Profile/Mypage/index.tsx
  src/pages/Profile/Mypage/style.scss
  src/pages/Profile/QuestList/index.tsx
  src/pages/Profile/QuestList/style.scss
  src/pages/Profile/RoadmapList/index.tsx
  src/pages/Profile/RoadmapList/style.scss
  src/pages/Profile/achievement_data.json
  src/pages/Profile/index.tsx
  src/pages/Profile/profile.stories.tsx
  src/pages/Profile/style.scss
  src/pages/Quest/QuestList/index.tsx
  src/pages/Quest/QuestList/style.scss
  src/styles/_color.scss
Labels: feature
