Repository YAPP-19th/Web-Team-1-Frontend, pull requests merged in 2022-01, with the labels that each got.

#40 [GILJOB-127] 랜딩 페이지 기능 개발 및 백엔드 연결
  package-lock.json
  package.json
  src/components/atoms/InfoCountItem/index.tsx
  src/components/atoms/InfoCountItem/style.scss
  src/components/atoms/Text/index.tsx
  src/components/atoms/index.ts
  src/components/molecules/InfoCount/index.tsx
  src/components/molecules/InfoCount/style.scss
  src/components/molecules/index.ts
  src/hooks/useScrollCount.ts
  src/pages/Landing/Contents/list.ts
  src/pages/Landing/Count/index.tsx
  src/pages/Landing/Count/list.ts
  src/pages/Landing/Count/style.scss
  src/pages/Landing/Main/index.tsx
Labels: environment, feature, refactor

#43 [GILJOB-122] 로드맵 생성 페이지 백엔드 연동
  src/components/atoms/Input/index.tsx
  src/components/atoms/SearchBar/index.tsx
  src/components/molecules/DragDrop/dragdrop.stories.tsx
  src/components/molecules/DragDrop/index.tsx
  src/components/molecules/Hashtag/index.tsx
  src/pages/CreateQuest/Sub/index.tsx
  src/pages/CreateRoadmap/Detail/index.tsx
  src/pages/CreateRoadmap/Detail/style.scss
  src/pages/CreateRoadmap/Main/index.tsx
  src/pages/CreateRoadmap/index.tsx
  src/services/giljob.ts
  src/services/types/request.ts
  src/services/types/response.ts
  src/slices/createQuestSlice.ts
  src/slices/createRoadmapSlice.ts
Labels: feature

#42 [GILJOB-122] 퀘스트 생성 페이지 백엔드 연동 및 로딩 & 토스트 컴포넌트 추가
  src/App.tsx
  src/assets/lottie/loading.json
  src/components/atoms/Editor/index.tsx
  src/components/atoms/Input/index.tsx
  src/components/atoms/Loading/index.tsx
  src/components/atoms/Loading/loading.stories.tsx
  src/components/atoms/Loading/style.scss
  src/components/atoms/SearchBar/index.tsx
  src/components/atoms/Toast/index.tsx
  src/components/atoms/Toast/style.scss
  src/components/atoms/Toast/toast.stories.tsx
  src/components/atoms/Uploader/index.tsx
  src/components/atoms/Uploader/style.scss
  src/components/atoms/index.ts
  src/components/molecules/DragDrop/dragdrop.stories.tsx
  src/components/molecules/DragDrop/index.tsx
  src/components/molecules/Hashtag/index.tsx
  src/hooks/useCheckState.ts
  src/index.tsx
  src/pages/CreateQuest/Main/index.tsx
  src/pages/CreateQuest/Sub/index.tsx
  src/pages/CreateQuest/index.tsx
  src/pages/CreateRoadmap/Detail/index.tsx
  src/pages/CreateRoadmap/Detail/style.scss
  src/pages/CreateRoadmap/Main/index.tsx
  src/pages/CreateRoadmap/index.tsx
  src/pages/Login/LoginBox/index.tsx
  src/pages/Login/RegisterBox/index.tsx
  src/services/giljob.ts
  src/services/types/request.ts
  src/services/types/response.ts
  src/slices/createQuestSlice.ts
  src/slices/createRoadmapSlice.ts
Labels: feature, refactor

#45 [GILJOB-122] 기타 컴포넌트 및 기능 추가, 구조 변경
  src/App.test.tsx
  src/App.tsx
  src/assets/images/floating.png
  src/assets/images/notfound.png
  src/components/atoms/Editor/index.tsx
  src/components/atoms/Floating/floating.stories.tsx
  src/components/atoms/Floating/index.tsx
  src/components/atoms/Floating/style.scss
  src/components/atoms/Input/index.tsx
  src/components/atoms/index.ts
  src/hooks/useDebounce.ts
  src/pages/CreateRoadmap/Detail/index.tsx
  src/pages/NotFound/NotFound.stories.tsx
  src/pages/NotFound/index.tsx
  src/pages/NotFound/style.scss
  src/services/giljob.ts
  src/services/types/request.ts
  src/services/types/response.ts
Labels: feature

#44 [GILJOB-122] feat: 변경된 API 스펙에 맞춰 쿼리를 수정한다.
  src/services/giljob.ts
  src/services/types/request.ts
  src/services/types/response.ts
Labels: feature, hotfix

#48 [GILJOB-129] Profile 페이지 기능 개발 및 백엔드 연결
  src/assets/images/achievement_1.svg
  src/assets/images/achievement_10.svg
  src/assets/images/achievement_2.svg
  src/assets/images/achievement_4.svg
  src/assets/images/achievement_5.svg
  src/assets/images/achievement_6.svg
  src/assets/images/achievement_7.svg
  src/assets/images/achievement_9.svg
  src/components/atoms/AchievementIcon/style.scss
  src/components/atoms/Badge/index.tsx
  src/components/atoms/Icon/style.scss
  src/components/atoms/Pagination/index.tsx
  src/components/atoms/ProgressBar/index.tsx
  src/components/atoms/Textarea/index.tsx
  src/components/molecules/ProfileQuestCard/index.tsx
  src/components/molecules/ProfileQuestCard/profileQuestCard.stories.tsx
  src/components/molecules/ProfileQuestCard/style.scss
  src/pages/Profile/Mypage/index.tsx
  src/pages/Profile/Mypage/style.scss
  src/pages/Profile/QuestList/index.tsx
  src/pages/Profile/QuestList/style.scss
  src/pages/Profile/RoadmapList/index.tsx
  src/pages/Profile/RoadmapList/style.scss
  src/pages/Profile/achievement_data.json
  src/pages/Profile/index.tsx
  src/pages/Profile/list.ts
  src/services/giljob.ts
  src/services/types/request.ts
  src/services/types/response.ts
  src/slices/profileSlice.ts
  src/store/index.ts
Labels: feature

#49 로드맵 생성 페이지 완성
  src/components/atoms/Pagination/index.tsx
  src/pages/CreateRoadmap/Detail/index.tsx
  src/pages/CreateRoadmap/Detail/style.scss
  src/pages/CreateRoadmap/Main/index.tsx
  src/pages/CreateRoadmap/Main/style.scss
  src/pages/CreateRoadmap/style.scss
  src/slices/createRoadmapSlice.ts
Labels: feature

#52 [GILJOB-161] favicon, 레벨 아이콘 추가
  config/webpack/webpack.dev.js
  config/webpack/webpack.prod.js
  public/favicon.ico
  src/assets/images/Lv10.svg
  src/assets/images/Lv11.svg
  src/assets/images/Lv12.svg
  src/assets/images/Lv13.svg
  src/assets/images/Lv14.svg
  src/assets/images/Lv15.svg
  src/assets/images/Lv16.svg
  src/assets/images/Lv17.svg
  src/assets/images/Lv18.svg
  src/assets/images/Lv19.svg
  src/assets/images/Lv20.svg
  src/assets/images/Lv6.svg
  src/assets/images/Lv7.svg
  src/assets/images/Lv8.svg
  src/assets/images/Lv9.svg
  src/components/atoms/Icon/style.scss
Labels: feature

#53 [GILJOB-93] 퀘스트 상세 페이지 개발
  src/App.tsx
  src/assets/images/pencil.png
  src/components/atoms/FloatingBar/index.tsx
  src/components/atoms/FloatingBar/style.scss
  src/components/atoms/MenuBar/index.tsx
  src/components/atoms/MenuBar/menubar.stories.tsx
  src/components/atoms/Pagination/index.tsx
  src/components/atoms/index.ts
  src/components/molecules/Paper/style.scss
  src/components/organisms/Roadmap/index.tsx
  src/components/organisms/Roadmap/style.scss
  src/hooks/useRoadmapModal.ts
  src/pages/Detail/DetailContent/index.tsx
  src/pages/Detail/DetailContent/style.scss
  src/pages/Detail/DetailDesc/index.tsx
  src/pages/Detail/DetailDesc/style.scss
  src/pages/Detail/DetailIntro/index.tsx
  src/pages/Detail/DetailIntro/style.scss
  src/pages/Detail/DetailQuestInteract/index.tsx
  src/pages/Detail/DetailQuestInteract/style.scss
  src/pages/Detail/DetailReview/index.tsx
  src/pages/Detail/DetailReview/style.scss
  src/pages/Detail/index.tsx
  src/pages/Detail/style.scss
  src/pages/Profile/RoadmapList/index.tsx
  src/pages/Quest/QuestList/index.tsx
  src/services/giljob.ts
  src/services/types/request.ts
  src/services/types/response.ts
  src/slices/questListSlice.ts
  src/slices/reviewListSlice.ts
  src/store/index.ts
Labels: feature, refactor, hotfix

#54 [GILJOB-122] 로드맵 생성 관련 문제 해결 및 컴포넌트 수정
  src/App.tsx
  src/assets/lottie/character.json
  src/assets/lottie/character.svg
  src/components/atoms/Input/style.scss
  src/components/atoms/List/list.stories.tsx
  src/components/molecules/DragDrop/dragdrop.stories.tsx
  src/components/molecules/DragDrop/index.tsx
  src/constants/createQuest/quest_data.json
  src/constants/createRoadmap/roadmap_data.json
  src/constants/landing/index.ts
  src/pages/CreateQuest/Detail/index.tsx
  src/pages/CreateQuest/Main/index.tsx
  src/pages/CreateQuest/Sub/index.tsx
  src/pages/CreateQuest/index.tsx
  src/pages/CreateRoadmap/Detail/index.tsx
  src/pages/CreateRoadmap/Main/index.tsx
  src/pages/CreateRoadmap/index.tsx
  src/pages/Landing/Contents/index.tsx
  src/pages/Landing/Main/index.tsx
  src/pages/Login/RegisterBox/index.tsx
  src/services/giljob.ts
  src/slices/createQuestSlice.ts
  src/slices/createRoadmapSlice.ts
  src/utils/handleDifficulty.ts
Labels: refactor, hotfix

#56 [GILJOB-162] 프로필 페이지 2차 QA 피드백 반영
  src/components/atoms/AchievementBadge/index.tsx
  src/components/atoms/Box/box.stories.tsx
  src/components/atoms/Loading/style.scss
  src/components/molecules/HeaderDropdown/index.tsx
  src/components/molecules/ProfileQuestCard/index.tsx
  src/components/molecules/ProfileQuestCard/profileQuestCard.stories.tsx
  src/components/molecules/ProfileQuestCard/style.scss
  src/pages/Detail/DetailIntro/index.tsx
  src/pages/Detail/DetailReview/index.tsx
  src/pages/Profile/Achievement/index.tsx
  src/pages/Profile/Mypage/index.tsx
  src/pages/Profile/QuestList/index.tsx
  src/pages/Profile/QuestList/style.scss
  src/pages/Profile/RoadmapList/style.scss
  src/pages/Quest/QuestList/index.tsx
  src/pages/Quest/RoadmapList/index.tsx
  src/services/giljob.ts
Labels: hotfix

#58 [GILJOB-125] 2차 QA
  src/components/atoms/Checkbox/index.tsx
  src/components/atoms/Modal/style.scss
  src/components/atoms/Text/index.tsx
  src/components/molecules/Card/index.tsx
  src/components/organisms/Roadmap/index.tsx
  src/components/organisms/Roadmap/roadmap.stories.tsx
  src/hooks/useQuestModal.ts
  src/hooks/useRoadmapModal.ts
  src/pages/CreateRoadmap/Detail/index.tsx
  src/pages/CreateRoadmap/index.tsx
  src/pages/Detail/DetailDesc/index.tsx
  src/pages/Detail/DetailQuestInteract/index.tsx
  src/pages/Detail/DetailReview/index.tsx
  src/pages/Detail/index.tsx
  src/pages/Quest/QuestList/style.scss
  src/pages/Quest/RoadmapList/index.tsx
  src/services/giljob.ts
Labels: error, hotfix

#57 [GILJOB-169] 컴포넌트 수정 사항 적용 / 2차 QA
  src/assets/images/floating_close.png
  src/assets/images/floating_open.png
  src/components/atoms/Floating/index.tsx
  src/components/atoms/Floating/style.scss
  src/components/atoms/Textarea/style.scss
  src/components/molecules/Header/index.tsx
  src/components/molecules/Header/style.scss
  src/components/molecules/HeaderDropdown/style.scss
  src/hooks/useCheckState.ts
  src/pages/CreateQuest/index.tsx
  src/pages/CreateRoadmap/index.tsx
  src/slices/createQuestSlice.ts
Labels: feature, hotfix

#60 [GILJOB-172] 2차 QA 피드백 반영
  src/components/atoms/Badge/style.scss
  src/components/molecules/Card/index.tsx
  src/components/molecules/Card/style.scss
  src/components/molecules/HeaderDropdown/index.tsx
  src/components/molecules/ProfileQuestCard/index.tsx
  src/components/molecules/ProfileQuestCard/style.scss
  src/pages/Quest/QuestList/index.tsx
Labels: hotfix

#61 [GILJOB-169] feat: 퀘스트 생성 기타 수정
  src/constants/dropdown/index.ts
  src/pages/CreateQuest/Main/index.tsx
  src/pages/CreateQuest/index.tsx
  src/pages/CreateQuest/style.scss
  src/pages/CreateRoadmap/style.scss
  src/slices/createQuestSlice.ts
Labels: feature, hotfix
